// <auto-generated />
using System;
using System.Text.Json;
using HockeyHub.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HockeyHub.Data.Data.Migrations
{
    [DbContext(typeof(HockeyHubDbContext))]
    [Migration("20260321042116_AddGamesAndStandings")]
    partial class AddGamesAndStandings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayBenchSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeBenchSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IceLengthFeet")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("IceWidthFeet")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<JsonDocument>("LayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PenaltyBoxSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Arenas");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.FranchiseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousLocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("FranchiseHistories");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AwayFaceoffPct")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int?>("AwayGiveaways")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayHits")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayPowerPlayGoals")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayPowerPlayOpps")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayShotsOnGoal")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTakeaways")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("AwayTimeOnAttack")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("ClockLastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ClockRunning")
                        .HasColumnType("boolean");

                    b.Property<int?>("CurrentPeriod")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentPeriodLabel")
                        .HasColumnType("text");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("GameDateLocal")
                        .HasColumnType("date");

                    b.Property<decimal?>("HomeFaceoffPct")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int?>("HomeGiveaways")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeHits")
                        .HasColumnType("integer");

                    b.Property<int?>("HomePowerPlayGoals")
                        .HasColumnType("integer");

                    b.Property<int?>("HomePowerPlayOpps")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeShotsOnGoal")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTakeaways")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HomeTimeOnAttack")
                        .HasColumnType("interval");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShootout")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeriodTimeRemaining")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodTimeRemainingSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("GameDateLocal");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("Status");

                    b.HasIndex("SeasonId", "GameDateLocal");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.GamePeriodScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("AwayShots")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<int>("HomeShots")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Period")
                        .IsUnique();

                    b.ToTable("GamePeriodScores");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FormerPlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormerPlayerId");

                    b.HasIndex("TeamId", "Role");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthStateProvince")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEbug")
                        .HasColumnType("boolean");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShootsCatches")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("DraftTeamId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent");

                    b.HasIndex("LeagueId", "YearStart")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.StandingsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FaceoffPct")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeagueRank")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeLosses")
                        .HasColumnType("integer");

                    b.Property<decimal>("PenaltyKillPct")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointsPct")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal>("PowerPlayPct")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("RegulationPlusOTWins")
                        .HasColumnType("integer");

                    b.Property<int>("RegulationWins")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueRank");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("StandingsSnapshots");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JoinedSeasonYear")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OriginalJoinYear")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StanleyCupsSince1973")
                        .HasColumnType("integer");

                    b.Property<int>("StanleyCupsSince2006")
                        .HasColumnType("integer");

                    b.Property<int>("StanleyCupsTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("LeagueId");

                    b.HasIndex("LocationName");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Arena", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.FranchiseHistory", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "CurrentTeam")
                        .WithMany("FranchiseHistories")
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTeam");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Game", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId");

                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyHub.Core.Models.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.GamePeriodScore", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Game", "Game")
                        .WithMany("PeriodScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Personnel", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Player", "FormerPlayer")
                        .WithMany()
                        .HasForeignKey("FormerPlayerId");

                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "Team")
                        .WithMany("Personnel")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormerPlayer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Player", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "CurrentTeam")
                        .WithMany("Players")
                        .HasForeignKey("CurrentTeamId");

                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "DraftTeam")
                        .WithMany()
                        .HasForeignKey("DraftTeamId");

                    b.Navigation("CurrentTeam");

                    b.Navigation("DraftTeam");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Season", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.StandingsSnapshot", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyHub.Core.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Team", b =>
                {
                    b.HasOne("HockeyHub.Core.Models.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Game", b =>
                {
                    b.Navigation("PeriodScores");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("HockeyHub.Core.Models.Entities.Team", b =>
                {
                    b.Navigation("FranchiseHistories");

                    b.Navigation("Personnel");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
