// <auto-generated />
using System;
using System.Text.Json;
using HockeyHub.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HockeyHub.Data.Data.Migrations
{
    [DbContext(typeof(HockeyHubDbContext))]
    partial class HockeyHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayBenchSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeBenchSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IceLengthFeet")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("IceWidthFeet")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<JsonDocument>("LayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PenaltyBoxSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Arenas");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.FranchiseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousLocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("FranchiseHistories");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FormerPlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormerPlayerId");

                    b.HasIndex("TeamId", "Role");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthStateProvince")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEbug")
                        .HasColumnType("boolean");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShootsCatches")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("DraftTeamId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent");

                    b.HasIndex("LeagueId", "YearStart")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JoinedSeasonYear")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OriginalJoinYear")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StanleyCupsSince1973")
                        .HasColumnType("integer");

                    b.Property<int>("StanleyCupsSince2006")
                        .HasColumnType("integer");

                    b.Property<int>("StanleyCupsTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("LeagueId");

                    b.HasIndex("LocationName");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Arena", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.FranchiseHistory", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.Team", "CurrentTeam")
                        .WithMany("FranchiseHistories")
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTeam");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Personnel", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.Player", "FormerPlayer")
                        .WithMany()
                        .HasForeignKey("FormerPlayerId");

                    b.HasOne("HockeyHub.Api.Models.Entities.Team", "Team")
                        .WithMany("Personnel")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormerPlayer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Player", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.Team", "CurrentTeam")
                        .WithMany("Players")
                        .HasForeignKey("CurrentTeamId");

                    b.HasOne("HockeyHub.Api.Models.Entities.Team", "DraftTeam")
                        .WithMany()
                        .HasForeignKey("DraftTeamId");

                    b.Navigation("CurrentTeam");

                    b.Navigation("DraftTeam");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Season", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Team", b =>
                {
                    b.HasOne("HockeyHub.Api.Models.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("HockeyHub.Api.Models.Entities.Team", b =>
                {
                    b.Navigation("FranchiseHistories");

                    b.Navigation("Personnel");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
